# Generated by Django 3.1 on 2019-12-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'manga', 'verbose_name_plural': 'mangas'},
        ),
    ]
