# Generated by Django 3.1 on 2019-12-05 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0002_auto_20191205_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryVideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Manga', 'verbose_name_plural': 'Mangas'},
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='type_manga',
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(verbose_name='Date de sortie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryVideoGame')),
            ],
            options={
                'verbose_name': 'Jeu vidéo',
                'verbose_name_plural': 'Jeux vidéos',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de sortie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryAnime')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
            },
        ),
        migrations.AddField(
            model_name='manga',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryManga'),
        ),
    ]
