# Generated by Django 3.1 on 2019-12-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0003_auto_20191205_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryAnime'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryVideoGame'),
        ),
    ]
