# Generated by Django 3.1 on 2019-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0005_auto_20191205_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='creator',
            field=models.CharField(default='CREATOR', max_length=200),
        ),
    ]
