# Generated by Django 3.1 on 2019-12-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0007_auto_20191205_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='realisator',
            field=models.CharField(default='REALISATOR', max_length=255, verbose_name='Réalisateur'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryAnime', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='author',
            field=models.CharField(default='AUTHOR', max_length=255, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryManga', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mangamers.CategoryVideoGame', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='creator',
            field=models.CharField(default='CREATOR', max_length=200, verbose_name='Créateur'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
