# Generated by Django 3.1 on 2019-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mangamers', '0008_auto_20191205_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='platform',
            field=models.CharField(max_length=100, null=True, verbose_name='Plateforme'),
        ),
        migrations.AlterField(
            model_name='categoryanime',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categorymanga',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='categoryvideogame',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
    ]
